### PR TITLE
Fix kick chat

### PR DESCRIPTION
**Pull request by cohlexyz**
Not sure what your local changes look like but these changes fixed Kick chat for me. The initial issue seemed to be missing members in the chat message object. After adding them the messages started showing up again but the emotes were broken which was fixed by populating the emoji array.

I don't know why missing variables would suddenly cause an issue.

I tried looking into Odysee but I could not find a single running stream for testing.

### CODE REVIEW

**Comment by ghost** [comment]
Are we back to using the individual site scripts in `feed` again instead of `seed.js`?

**Comment by jaw-sh** [comment]
No, it should all be in that one file. I didn't notice.

**Comment by cohlexyz** [comment]
Well fuck. The fix is still the same, though. It's missing the `is_premium` member variable.

**Comment by jaw-sh** [comment]
i don't think that's it. in the live thing it works for a second and then breaks after some seconds.

**Comment by cohlexyz** [comment]
I sadly can't seem to reproduce that issue, which makes it a bit hard to diagnose.

**Comment by cohlexyz** [comment]
As for the Rumble dependency issue, is there any reason we use UUIDv5? We could get rid of the dependency and just use v4 which is a lot simpler to just implement right in the user script:
```js
function uuidv4() {
  return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, c =>
    (+c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> +c / 4).toString(16)
  );
}
```
Using this in seed.js and replacing the usage of UUID.v5 with it worked fine for me.

**Comment by ghost** [comment]
Or just [Crypto.randomUUID()](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID), which does v4. I think we used it at one point before he opted for v5.

**Comment by jaw-sh** [comment]
yes, I want deterministic UUIDs.

**Comment by ghost** [comment]
What about doing a simple hash of the username+platform? It's already something similar to what v5 does, but you don't need the import.

**Comment by jaw-sh** [comment]
that's a really cool idea but rust uses a strict type for the json and it must be a uuid.

**Comment by ghost** [comment]
It can't be a string or byte array or something?

**Comment by jaw-sh** [comment]
dog

I would much, much, much, much rather have currency conversions working or Facebook Live integration or literally anything besides spending time completely rewriting the way UUIDs work throughout the program.

**Comment by ghost** [comment]
lol fair

**Pull request merged**
