### PR TITLE
Add X/Twitter chat support

### PR DESCRIPTION
**Pull request by ghost**
Got chat working for the artist formerly known as Twitter. I don't know what identifiers broadcasters or subscribers have, if any. I'm not sure if there are premium chats either.

Their selectors are pure garbage, so I had to rely highly on the hierarchy.

### CODE REVIEW

**Comment by jaw-sh** [comment]
Are there no websockets?

**Comment by ghost** [comment]
I haven't checked. I should start taking a look at that for all of the services, where possible.

**Comment by ghost** [comment]
It appears to go through numerous post requests to /chatapi/v1/history

Edit: This may just be for replayed streams. However, I would imagine they don't use WebSockets for live stuff either if they don't do it here.

Edit 2: I found `wss://prod-chatman-ancillary-us-east-1.pscp.tv/chatapi/v1/chatnow` while poking around in Spaces. It gives a feed that is identical to the history calls I was seeing earlier so parsing code could be reused easily.

**Comment by ghost** [comment]
You can search for broadcasts using the `url` operator which searches expanded URLs. Just figured this out.

i.e. `url:broadcasts` to match the `/i/broadcasts` part of the stream URL.

**Comment by jaw-sh** [comment]
I'm in the middle (about 75% done) of a huge update to switch off dom observation.

that's an incredible tip btw

**Comment by ghost** [comment]
Yeah I'm glad I was able to figure something out. It was driving me crazy.
There's a lot of handy info [here](https://developer.twitter.com/en/docs/twitter-api/enterprise/search-api/guides/operators)

**Pull request merged**
